# Preprocesamiento de datos de COVID
### Curso: Machine Learning

**Integrantes:**
- Manuel Laura
- Aydee Carolina Zapana Caillahua
- Absalon Chambilla Condori

**Docente:** Miguel Romilio Aceituno Rojo

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import kagglehub,os
os.environ["KAGGLE_API_TOKEN"] = "KGAT_10545264f6b54e0bd995ca4fd9829565"

path = kagglehub.dataset_download("manuellaura/covid-puno")

Downloading to /root/.cache/kagglehub/datasets/manuellaura/covid-puno/1.archive...

100%|██████████| 4.40M/4.40M [00:00<00:00, 38.7MB/s]

Extracting files...

In [ ]:
df = pd.read_csv(path+"/covid.csv", low_memory=False, encoding='utf-8')

In [ ]:
df

,id,ano,semana,fecha_not,diresa,red,microred,establecimiento,institucion,clasificacion,...,prueba_rap,resultado_rap,fecha_res_rap,fecha_rap1,muestra_rap1,prueba_rap1,resultado_rap1,fecha_res_rap1,secuenciamiento,asintomatico
0,542,2021,5,09-02-2021,PUNO,PUNO,SIN MICRORED,"HOSP. REG. ""MANUEL NUÑEZ BUTRÓN"" - PUNO",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,00-00-0000,NaN,NaN,NaN,NaN,NaN,NaN
1,1234,2020,10,07-03-2020,PUNO,SAN ROMAN,SIN MICRORED,"HOSP. ""CARLOS MONGE MEDRANO"" - JULIACA",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1258,2020,10,09-03-2020,PUNO,PUNO,SIN MICRORED,HOSPITAL III DE ESSALUD,ESSALUD,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1266,2020,10,09-03-2020,PUNO,SAN ROMAN,SIN MICRORED,"HOSP. ""CARLOS MONGE MEDRANO"" - JULIACA",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1292,2021,9,05-03-2021,PUNO,PUNO,METROPOLITANO,C.S. METROPOLITANO PUNO,GOBIERNO REGIONAL,CONFIRMADO,...,SEROLOGIA,NEGATIVO,16-07-2020,00-00-0000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95310,8431803,2021,20,23-05-2021,PUNO,AZANGARO,ASILLO,C.S. ASILLO,GOBIERNO REGIONAL,CONFIRMADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95311,8431821,2021,20,24-05-2021,PUNO,AZANGARO,SAN ANTÓN,C.S. SAN ANTÓN,GOBIERNO REGIONAL,CONFIRMADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95312,8431830,2021,20,24-05-2021,PUNO,AZANGARO,CHUPA,C.S. CHUPA,GOBIERNO REGIONAL,CONFIRMADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95313,8431915,2021,17,24-05-2021,PUNO,AZANGARO,ALIANZA,C.S. SAN JOSÉ,GOBIERNO REGIONAL,CONFIRMADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95314,8431927,2021,20,23-05-2021,PUNO,AZANGARO,ALIANZA,C.S. SAN JOSÉ,GOBIERNO REGIONAL,CONFIRMADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Porcentaje de nulos por columna

In [ ]:
pd.set_option('display.max_rows', None)
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

otro_hos                   100.000000
secuenciamiento            100.000000
ciudad_3                    99.846824
entrada                     99.643288
contacto_otro               99.619158
servicio_otro               99.284478
resultado2                  99.191103
prueba2                     99.163825
muestra2                    99.163825
ciudad_2                    99.100876
entorno_otro                99.069401
profesion                   98.063264
mercado_localidad           97.964644
eess_trabajo                97.902744
provincia_mercado           97.897498
departamento_mercado        97.897498
contacto_mercado            97.897498
microred_trabajo            97.870220
lugar_def                   97.531343
red_trabajo                 97.492525
diresa_trabajo              97.469443
servicio                    97.284793
diagnostico_ing             97.140009
distrito_trabajo            96.479043
departamento_trabajo        96.479043
provincia_trabajo           96.479043
ubigeo_trabajo              96.132823
seguro                      95.995384
esalud_14                   95.956565
resultado1                  95.743587
prueba1                     95.658606
muestra1                    95.632377
otros_sintomas              94.255888
eess                        93.752295
neumonia                    93.312700
entubado                    93.204637
contacto_localidad          92.795468
prueba_rap1                 92.548917
ciudad_1                    92.532130
contacto_ubigeo             92.414625
provincia_contacto          92.414625
departamento_contacto       92.414625
fecha_res_rap1              92.410429
resultado_rap1              92.395740
muestra_rap1                92.392593
otros_signos                88.234800
migrante                    85.910927
otros_comorbilidad          85.102030
distrito_infeccion          80.850863
provincia_infeccion         80.850863
departamento_infeccion      80.850863
ubigeo_infeccion            80.553953
nacionalidad                75.178094
evolucion                   70.793684
ecografia_hos               66.004302
convulsion_hos              66.004302
rmn_hos                     66.003252
coma_hos                    66.003252
tomografia_hos              66.000105
radiografia_hos             65.967581
disnea_hos                  65.964434
auscultacion_hos            65.952893
ventilacion                 64.835545
resultado                   61.349211
casa_reposo                 61.079578
fecha_res2                  61.079578
albergue                    61.079578
obesidad                    61.079578
asma                        61.079578
tbc                         61.079578
culmina_embarazo            61.079578
ecografia                   61.079578
rmn                         61.079578
tomografia                  61.079578
fecha_alt                   61.079578
ageusia                     61.079578
oido                        61.079578
peso                        61.079578
pais_origen                 61.079578
pais_nacionalidad           61.079578
talla                       61.079578
centro_penitenciario        61.079578
hora_def                    61.079578
anosmia                     61.079578
fecha_mue2                  61.079578
prueba                      60.545559
muestra                     59.854168
asintomatico                59.114515
punto                       51.499764
prueba_rap                  35.874731
mercado                     35.247338
fecha_res_rap               34.719614
muestra_rap                 34.220217
resultado_rap               34.189792
otra_ocupacion              33.167917
fecha_rap1                  30.067670
fecha_rap                   30.066621
pais_3                      30.055081
temperatura                 30.055081
pais_1                      30.055081
pais_2                      30.055081
eess_14                     30.055081
mercado_pais                30.055081
viajado_14                  30.055081
contacto_pais               30.055081
contacto_trabajo            30.055081
fecha_det                   30.055081
aislamiento                 30.055081
hepatico                    30.055081
coma                        30.055081
contacto_14                 30.055081
contacto_salud              30.055081
contacto_familiar           30.055081
contacto_desconocido        30.055081
etnia                       16.322719
microred                     0.101768
departamento_residencia      0.022032
provincia_residencia         0.022032
residencia                   0.022032
institucion                  0.017836
establecimiento              0.017836
ubigeo                       0.017836
fecha_res1                   0.010492
fecha_mue1                   0.010492
clasificacion                0.004197
semana                       0.000000
ano                          0.000000
diresa                       0.000000
sexo                         0.000000
red                          0.000000
fecha_not                    0.000000
fecha_ais                    0.000000
fecha_ini                    0.000000
hospitalizado                0.000000
fecha_hos                    0.000000
pais_residencia              0.000000
edad                         0.000000
tipo_edad                    0.000000
id                           0.000000
pulmonar                     0.000000
articulaciones               0.000000
muscular                     0.000000
abdominal                    0.000000
exudado                      0.000000
conjuntival                  0.000000
convulsion                   0.000000
disnea                       0.000000
malestar                     0.000000
cancer                       0.000000
ocupacion                    0.000000
cardiovascular               0.000000
hepatica                     0.000000
auscultacion                 0.000000
embarazo                     0.000000
rxpulmonar                   0.000000
trimestre                    0.000000
postparto                    0.000000
diabetes                     0.000000
renal                        0.000000
inmunodeficiencia            0.000000
neurologica                  0.000000
fiebre                       0.000000
fecha_def                    0.000000
nauseas                      0.000000
diarrea                      0.000000
respiratoria                 0.000000
congestion                   0.000000
garganta                     0.000000
tos                          0.000000
cefalea                      0.000000
irritabilidad                0.000000
pecho                        0.000000
entorno_desconocido          0.000000
confirmado_14                0.000000
entorno_trabajo              0.000000
entorno_familiar             0.000000
entorno_salud                0.000000
fecha_res                    0.000000
fecha_mue                    0.000000
dtype: float64

## Eliminar columnas NAN >95%

In [ ]:
null_pct = df.isna().mean()
cols_to_drop = null_pct[null_pct > 0.96].index
df_clean = df.drop(columns=cols_to_drop)

print(f"Eliminado {len(cols_to_drop)} columnas: {list(cols_to_drop)}")

Eliminado 27 columnas: ['entrada', 'diagnostico_ing', 'otro_hos', 'servicio', 'servicio_otro', 'lugar_def', 'profesion', 'diresa_trabajo', 'red_trabajo', 'microred_trabajo', 'eess_trabajo', 'departamento_trabajo', 'provincia_trabajo', 'distrito_trabajo', 'ubigeo_trabajo', 'ciudad_2', 'ciudad_3', 'contacto_otro', 'entorno_otro', 'departamento_mercado', 'provincia_mercado', 'contacto_mercado', 'mercado_localidad', 'muestra2', 'prueba2', 'resultado2', 'secuenciamiento']

In [ ]:
df_clean.dtypes

id                           int64
ano                          int64
semana                       int64
fecha_not                   object
diresa                      object
red                         object
microred                    object
establecimiento             object
institucion                 object
clasificacion               object
punto                       object
fecha_det                   object
edad                         int64
tipo_edad                   object
sexo                        object
peso                       float64
talla                      float64
nacionalidad                object
pais_nacionalidad           object
migrante                    object
pais_origen                 object
pais_residencia             object
departamento_residencia     object
provincia_residencia        object
residencia                  object
ubigeo                      object
etnia                       object
fecha_ini                   object
departamento_infeccion      object
provincia_infeccion         object
distrito_infeccion          object
ubigeo_infeccion            object
hospitalizado               object
fecha_hos                   object
eess                        object
seguro                      object
aislamiento                 object
fecha_ais                   object
convulsion_hos             float64
disnea_hos                 float64
coma_hos                   float64
auscultacion_hos           float64
radiografia_hos            float64
ecografia_hos              float64
tomografia_hos             float64
rmn_hos                    float64
ventilacion                 object
entubado                    object
neumonia                    object
evolucion                   object
fecha_alt                   object
fecha_def                   object
hora_def                   float64
fiebre                       int64
malestar                     int64
tos                          int64
garganta                     int64
congestion                   int64
respiratoria                 int64
diarrea                      int64
nauseas                      int64
cefalea                      int64
irritabilidad                int64
muscular                     int64
abdominal                    int64
pecho                        int64
articulaciones               int64
anosmia                    float64
ageusia                    float64
oido                       float64
otros_sintomas              object
temperatura                float64
exudado                      int64
conjuntival                  int64
convulsion                   int64
coma                       float64
disnea                       int64
auscultacion                 int64
rxpulmonar                   int64
ecografia                  float64
tomografia                 float64
rmn                        float64
otros_signos                object
embarazo                     int64
trimestre                    int64
postparto                    int64
cardiovascular               int64
diabetes                     int64
hepatica                     int64
neurologica                  int64
inmunodeficiencia            int64
renal                        int64
hepatico                   float64
pulmonar                     int64
cancer                       int64
obesidad                   float64
tbc                        float64
asma                       float64
otros_comorbilidad          object
culmina_embarazo            object
ocupacion                   object
otra_ocupacion              object
viajado_14                  object
pais_1                      object
ciudad_1                    object
pais_2                      object
pais_3                      object
eess_14                     object
esalud_14                   object
contacto_14                 object
contacto_salud             float64
contacto_familiar          float64
contacto_trabajo           float64
contacto_desconocido       float64
confirmado_14               object
entorno_salud                int64
entorno_familiar             int64
entorno_trabajo              int64
casa_reposo                float64
centro_penitenciario       float64
albergue                   float64
entorno_desconocido          int64
contacto_pais               object
departamento_contacto       object
provincia_contacto          object
contacto_ubigeo             object
contacto_localidad          object
mercado                     object
mercado_pais                object
fecha_mue                   object
muestra                     object
prueba                      object
resultado                   object
fecha_res                   object
fecha_mue1                  object
muestra1                    object
prueba1                     object
resultado1                  object
fecha_res1                  object
fecha_mue2                  object
fecha_res2                  object
fecha_rap                   object
muestra_rap                 object
prueba_rap                  object
resultado_rap               object
fecha_res_rap               object
fecha_rap1                  object
muestra_rap1                object
prueba_rap1                 object
resultado_rap1              object
fecha_res_rap1              object
asintomatico                object
dtype: object

In [ ]:
df_clean.nunique().sort_values(ascending=True)

diresa                         1
asintomatico                   1
muestra_rap1                   1
muestra_rap                    1
diarrea                        2
sexo                           2
migrante                       2
nacionalidad                   2
coma_hos                       2
auscultacion_hos               2
garganta                       2
congestion                     2
muscular                       2
respiratoria                   2
rmn_hos                        2
entubado                       2
neumonia                       2
tos                            2
malestar                       2
fiebre                         2
tomografia_hos                 2
aislamiento                    2
disnea_hos                     2
convulsion_hos                 2
radiografia_hos                2
ecografia_hos                  2
entorno_salud                  2
entorno_familiar               2
casa_reposo                    2
irritabilidad                  2
cefalea                        2
nauseas                        2
tbc                            2
asma                           2
contacto_familiar              2
contacto_salud                 2
renal                          2
inmunodeficiencia              2
obesidad                       2
cancer                         2
hepatica                       2
neurologica                    2
cardiovascular                 2
diabetes                       2
postparto                      2
embarazo                       2
pulmonar                       2
hepatico                       2
tomografia                     2
rmn                            2
ecografia                      2
rxpulmonar                     2
coma                           2
convulsion                     2
auscultacion                   2
disnea                         2
exudado                        2
conjuntival                    2
oido                           2
ageusia                        2
anosmia                        2
entorno_trabajo                2
centro_penitenciario           2
albergue                       2
contacto_trabajo               2
entorno_desconocido            2
contacto_desconocido           2
resultado1                     2
resultado                      2
articulaciones                 2
pecho                          2
abdominal                      2
mercado                        3
confirmado_14                  3
viajado_14                     3
punto                          3
ventilacion                    3
hospitalizado                  3
ano                            3
tipo_edad                      3
contacto_14                    3
eess_14                        3
resultado_rap1                 4
muestra1                       4
muestra                        4
clasificacion                  4
seguro                         4
resultado_rap                  4
institucion                    5
etnia                          5
evolucion                      5
ocupacion                      7
pais_3                         8
contacto_pais                 10
prueba1                       10
trimestre                     10
red                           12
departamento_infeccion        13
pais_2                        15
pais_nacionalidad             17
departamento_contacto         17
pais_origen                   18
mercado_pais                  19
pais_1                        23
pais_residencia               23
departamento_residencia       25
temperatura                   31
provincia_infeccion           31
prueba                        32
prueba_rap1                   40
provincia_contacto            43
eess                          53
semana                        53
microred                      63
prueba_rap                   100
provincia_residencia         101
edad                         104
distrito_infeccion           143
ubigeo_infeccion             145
contacto_ubigeo              145
fecha_res2                   147
fecha_mue2                   147
culmina_embarazo             171
hora_def                     200
fecha_det                    219
talla                        219
fecha_res_rap1               224
fecha_rap1                   226
fecha_res1                   246
contacto_localidad           247
fecha_mue1                   255
fecha_rap                    262
fecha_res_rap                262
fecha_def                    322
fecha_alt                    324
residencia                   326
esalud_14                    327
ubigeo                       334
establecimiento              344
peso                         366
fecha_hos                    408
fecha_mue                    446
fecha_not                    456
fecha_ais                    459
fecha_ini                    463
fecha_res                    464
otros_signos                 778
ciudad_1                     802
otros_comorbilidad          1194
otros_sintomas              1211
otra_ocupacion              5970
id                         95315
dtype: int64

In [ ]:
df_clean['asintomatico'].value_counts()

asintomatico
SI    38970
Name: count, dtype: int64

In [ ]:
df_clean['asintomatico']=df_clean['asintomatico'].fillna('NO')

In [ ]:
df_clean['diresa'].value_counts()

diresa
PUNO    95315
Name: count, dtype: int64

In [ ]:
df_clean['diresa']=df_clean['diresa'].fillna('SIN DIRESA')

In [ ]:
print(df_clean['muestra_rap1'].value_counts())
print(df_clean['muestra_rap'].value_counts())

muestra_rap1
MUESTRA DE SANGRE    7251
Name: count, dtype: int64
muestra_rap
MUESTRA DE SANGRE    62698
Name: count, dtype: int64

In [ ]:
df_clean['muestra_rap']=df_clean['muestra_rap'].fillna('SIN MUESTRA')
df_clean['muestra_rap1']=df_clean['muestra_rap1'].fillna('SIN MUESTRA')

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Columns: 152 entries, id to asintomatico
dtypes: float64(30), int64(39), object(83)
memory usage: 110.5+ MB

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
columnas_demograficas = [
    'microred',
    'establecimiento',
    'institucion',
    'clasificacion',
    'punto',
    'nacionalidad',
    'pais_nacionalidad',
    'migrante',
    'pais_origen',
    'departamento_residencia',
    'provincia_residencia',
    'residencia',
    'ubigeo',
    'etnia',
    'departamento_infeccion',
    'provincia_infeccion',
    'distrito_infeccion',
    'ubigeo_infeccion',
    'eess',
    'seguro'
]

for col in columnas_demograficas:
    df_clean[col] = df_clean[col].fillna('NO REGISTRADO')

In [ ]:
columnas_datos_clinicos = [
    'aislamiento',
    'convulsion_hos',
    'disnea_hos',
    'coma_hos',
    'auscultacion_hos',
    'radiografia_hos',
    'ecografia_hos',
    'tomografia_hos',
    'rmn_hos'
]

for col in columnas_datos_clinicos:
    df_clean[col] = df_clean[col].fillna('NO REGISTRADO')

In [ ]:
columnas_datos_clinicos = [
    'peso',
    'talla',

    'aislamiento',
    'convulsion_hos',
    'disnea_hos',
    'coma_hos',
    'auscultacion_hos',
    'radiografia_hos',
    'ecografia_hos',
    'tomografia_hos',
    'rmn_hos',
    'ventilacion',
    'entubado',
    'neumonia',

    'evolucion',
    'fecha_alt',
    'hora_def',

    'anosmia',
    'ageusia',
    'oido',
    'otros_sintomas',
    'temperatura',
    'coma',
    'ecografia',
    'tomografia',
    'rmn',
    'otros_signos',

    'hepatico',
    'obesidad',
    'tbc',
    'asma',
    'otros_comorbilidad',

    'culmina_embarazo',
    'otra_ocupacion'
]

for col in columnas_datos_clinicos:
    df_clean[col] = df_clean[col].fillna('NO REGISTRADO')

COLUMNAS DE CONTACTO, DIAGNOSTICO y FECHAS DE DIAGNOSTICO

In [ ]:
col_diag_numerica=['contacto_salud',
 'contacto_familiar',
 'contacto_trabajo',
 'contacto_desconocido',
 'casa_reposo',
 'centro_penitenciario',
 'albergue']
for col in col_diag_numerica:
    df_clean[col]=df_clean[col].fillna(0).astype('int32')

In [ ]:
col_contacto = ['pais_1', 'pais_2', 'pais_3', 'contacto_pais', 'mercado_pais']
df_clean[col_contacto] = df_clean[col_contacto].apply(lambda x: x.str.upper()).fillna('SIN REGISTRO')

In [ ]:
col_contacto_prueba=[
    'ciudad_1',
'departamento_contacto',
'provincia_contacto',
'contacto_ubigeo',
'contacto_localidad',
    'muestra1',
    'prueba1',
    'resultado1',
    'prueba_rap',
    'prueba_rap1',
    'resultado_rap',
    'resultado_rap1'
]
df_clean[col_contacto_prueba] = df_clean[col_contacto_prueba].fillna('SIN REGISTRO')

df_clean['ciudad_1'] = df_clean['ciudad_1'].str.strip()
df_clean['ciudad_1'] = df_clean['ciudad_1'].replace('Juliaca', 'JULIACA')

In [ ]:
df_clean[[
    'viajado_14',
    'eess_14',
    'esalud_14',
    'contacto_14',
    'mercado'
]] = df_clean[
    ['viajado_14', 'eess_14', 'esalud_14', 'contacto_14','mercado']].fillna('DESCONOCIDO')

In [ ]:
colsrp = ['prueba_rap', 'prueba_rap1']

df_clean[colsrp] = df_clean[colsrp].apply(lambda x: x.str.strip())

df_clean[colsrp] = df_clean[colsrp].apply(lambda x: (
    x.str.replace('&nbsp;', ' ', regex=False)
     .str.replace(r'[\xa0\u200b\u2007\u202f\s]+', ' ', regex=True)
     .str.replace(r'[^\w\s]', '', regex=True)
     .str.upper()
))

df_clean[colsrp] = df_clean[colsrp].replace([
    'RAPIDO',
    'RPUEBA RAPIDA',
    'PRUEBA RAÁPIDA',
    'RPIDA',
    'RÀPIDA',
    'RAPIDA',
    'RÁPIDA',
    'RAPIDAR',
    'PRUEBA  RAPIDA',
    'PRUEVA RAPIDA',
    'PRUEBA RAPIDA COVID 19',
    'PRUEBA RAPIDA COVID19',
    'TEST RAPIDO PARA COVID 19',
    'PRUEVA RRAPIDA',
    'PR COVID 19',
    'R',
    'PRUEBA RAPIDA',
    'PR'
], 'PRUEBA RÁPIDA')

df_clean[colsrp] = df_clean[colsrp].replace([
    'SEROLOGIA',
    'SEROLOGICA',
    'SEROLOGICO',
    'SERELOGICA',
    'SEROLOGÍA',
    'PRUEBA SEROLOGICA',
    'SEROÓGICA',
    'S',
    'CEROLOGICA',
    'SEROLÓGICO',
    'SEROLIGICA'
], 'SEROLÓGICA')

df_clean[colsrp]=df_clean[colsrp].replace(
    ['SANGRE TOTAL',
     'RAPIDA SANGRE TOTAL',
     'RÁPIDA SANGRE TOTAL',
     'SANGRE',
     'MUESTRA DE SANGRE',
     'SANGREZ TOTAL'
    ],
    'PRUEBA RÁPIDA SANGRE TOTAL')

In [ ]:
datecols=['fecha_mue1','fecha_res1','fecha_mue2','fecha_res2','fecha_rap','fecha_rap1','fecha_res_rap','fecha_res_rap1']
for col in datecols:
    df[col] = pd.to_datetime(df[col], format='%d-%m-%Y', errors='coerce')